name: build
on: [push, pull_request]

permissions:
  contents: write

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [HTML5]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create export directory
        run: mkdir html5

      - name: Godot HTML5 export
        uses: dulvui/godot-4-html-export@v1
        with:
          godot-version: 4.3
