name: build
on: [push, pull_request]

permissions:
  contents: write

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [HTML5]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: manleydev/build-godot-action@v1.5.0
        with:
          name: whisperstone
          preset: HTML5
