name: Build
on:
  push:
    branches:
      - "main"      
    tags-ignore:
      - "*"

  pull_request:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [HTML5]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create export directory
        run: mkdir html5

      - name: Godot HTML5 export
        uses: dulvui/godot-4-html-export@v1.0.1
        with:
          godot-version: 4.3
          godot-channel: stable
          
      - name: Upload HTML5 Build
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        uses: actions/upload-artifact@v4
        with:
          name: html5
          path: html5/
