name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [HTML5]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if [[ $VERSION == *"alpha"* || $VERSION == *"beta"* || $VERSION == *"prerelease"* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Create export directory
        run: mkdir html5

      - name: Godot HTML5 export
        uses: dulvui/godot-4-html-export@v1.0.1
        with:
          godot-version: 4.3
          godot-channel: stable

      - name: Create ZIP archive
        run: |
          cd html5
          zip -r "../game-v${{ steps.get_version.outputs.version }}-html5.zip" .

      - name: Generate release notes
        id: release_notes
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREVIOUS_TAG" ]; then
            # If no previous tag exists, use the first commit
            echo "NOTES<<ENDOFNOTES" >> $GITHUB_OUTPUT
            git log --pretty=format:"- %s" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "ENDOFNOTES" >> $GITHUB_OUTPUT
          else
            echo "NOTES<<ENDOFNOTES" >> $GITHUB_OUTPUT
            git log --pretty=format:"- %s" $PREVIOUS_TAG..HEAD >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "ENDOFNOTES" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: game-v${{ steps.get_version.outputs.version }}-html5.zip
          prerelease: ${{ steps.get_version.outputs.is_prerelease }}
          body: |
            ## What's Changed
            ${{ steps.release_notes.outputs.NOTES }}
            
            ## Installation
            Download the ZIP file for your platform and extract it to play the game.
            
            ## Feedback
            If you encounter any issues, please report them in our issue tracker.
