name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Download HTML5 Build
        uses: actions/download-artifact@v3
        with:
          name: html5
          path: html5

      - name: Create ZIP Archive
        run: |
          cd html5
          zip -r ../game-html5.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: game-html5.zip
          draft: false
          prerelease: false
          generate_release_notes: true
